# Generated by Django 3.1.1 on 2020-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('console', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
