# Generated by Django 3.1.1 on 2020-09-15 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrp', '0002_historymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
